apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/ingress.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

patchesStrategicMerge:
- overlays/argocd-server-service.yaml
- overlays/argocd-server-deployment.yaml
- overlays/argocd-server-argocd-cm.yaml

namespace: argocd
 